#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times
#  but for the 9th iteration, displays hi and a new line
i=0
while [ $i -lt 10 ]; do
	if [ $i -eq 9 ]; then
		echo "Hi"
	fi
	echo "Best School"
	(( i++ ))
done
