#!/usr/bin/env bash
# Write a Bash script that displays
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

ls_list=$(ls)

for l in $ls_list; do
	echo "$l" | cut -d '-' -f2
done
