#!/usr/bin/env bash
# Run nginx as non-root user

# Add a new user
sudo adduser nginx

# Replace the root user with nginx
sudo sed -i 's/user www-data/user nginx' /etc/nginx/nginx.conf

# Nginx must be listening on all active IP on port 8080
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Provide user with necessary permissions
sudo chown -R nginx:nginx /etc/nginx/nginx.conf

# Restart nginx to persist changes
sudo -u nginx service nginx restart
